global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Library Management System - Updated for Docker networking
  - job_name: 'library-management'
    static_configs:
      - targets: ['library-app:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    params:
      format: ['prometheus']

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Zipkin metrics
  - job_name: 'zipkin'
    static_configs:
      - targets: ['zipkin:9411']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
