apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      tlsSkipVerify: true

  - name: Zipkin
    type: zipkin
    access: proxy
    url: http://zipkin:9411
    editable: true
    basicAuth: false
    jsonData:
      tlsSkipVerify: true
